// Package docker provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package docker

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ContainerDetailRestartPolicy.
const (
	Always        ContainerDetailRestartPolicy = "always"
	No            ContainerDetailRestartPolicy = "no"
	OnFailure     ContainerDetailRestartPolicy = "on-failure"
	UnlessStopped ContainerDetailRestartPolicy = "unless-stopped"
)

// Valid indicates whether the value is a known member of the ContainerDetailRestartPolicy enum.
func (e ContainerDetailRestartPolicy) Valid() bool {
	switch e {
	case Always:
		return true
	case No:
		return true
	case OnFailure:
		return true
	case UnlessStopped:
		return true
	default:
		return false
	}
}

// Defines values for ContainerStatus.
const (
	Dead       ContainerStatus = "dead"
	Paused     ContainerStatus = "paused"
	Restarting ContainerStatus = "restarting"
	Running    ContainerStatus = "running"
	Stopped    ContainerStatus = "stopped"
)

// Valid indicates whether the value is a known member of the ContainerStatus enum.
func (e ContainerStatus) Valid() bool {
	switch e {
	case Dead:
		return true
	case Paused:
		return true
	case Restarting:
		return true
	case Running:
		return true
	case Stopped:
		return true
	default:
		return false
	}
}

// Defines values for PortBindingProtocol.
const (
	Tcp PortBindingProtocol = "tcp"
	Udp PortBindingProtocol = "udp"
)

// Valid indicates whether the value is a known member of the PortBindingProtocol enum.
func (e PortBindingProtocol) Valid() bool {
	switch e {
	case Tcp:
		return true
	case Udp:
		return true
	default:
		return false
	}
}

// Defines values for VolumeMountMode.
const (
	Ro VolumeMountMode = "ro"
	Rw VolumeMountMode = "rw"
)

// Valid indicates whether the value is a known member of the VolumeMountMode enum.
func (e VolumeMountMode) Valid() bool {
	switch e {
	case Ro:
		return true
	case Rw:
		return true
	default:
		return false
	}
}

// Bytes A quantity expressed in bytes.
type Bytes = int64

// Container A container running on a Docker-compatible backend.
type Container struct {
	// Device Identifier of the backend device running this container.
	Device string `json:"device"`

	// Id Globally unique container identifier in the form `{device}.{name}`.
	// Use this value directly in path parameters.
	Id string `json:"id"`

	// Image Container image reference including tag or digest.
	Image string `json:"image"`

	// Name Container name as reported by the backend.
	Name string `json:"name"`

	// Resources Live resource usage for a container.
	Resources ContainerResources `json:"resources"`

	// RestartCount Number of times the container has been restarted.
	RestartCount int `json:"restartCount"`

	// Status Current state of a container.
	Status ContainerStatus `json:"status"`
}

// ContainerDetail defines model for ContainerDetail.
type ContainerDetail struct {
	// Cmd Default command arguments passed to the entrypoint.
	Cmd []string `json:"cmd"`

	// Device Identifier of the backend device running this container.
	Device string `json:"device"`

	// Entrypoint Container entrypoint command.
	Entrypoint []string `json:"entrypoint"`

	// EnvVariables Environment variables set in the container.
	EnvVariables []EnvVariable `json:"envVariables"`

	// ExitCode Exit code of the last process. Only meaningful when status is not 'running'.
	ExitCode int `json:"exitCode"`

	// FinishedAt Time the container last stopped. Omitted if the container is still running.
	FinishedAt *time.Time `json:"finishedAt,omitempty"`

	// Id Globally unique container identifier in the form `{device}.{name}`.
	// Use this value directly in path parameters.
	Id string `json:"id"`

	// Image Container image reference including tag or digest.
	Image string `json:"image"`

	// Labels Container labels as key-value pairs.
	Labels *map[string]string `json:"labels,omitempty"`

	// MemoryLimit Configured memory limit in bytes. 0 means unlimited.
	MemoryLimit Bytes `json:"memoryLimit"`

	// Name Container name as reported by the backend.
	Name string `json:"name"`

	// Networks Networks this container is attached to.
	Networks []ContainerNetwork `json:"networks"`

	// OomKilled Whether the container was killed due to an out-of-memory condition.
	OomKilled bool `json:"oomKilled"`

	// PortBindings Published port mappings between host and container.
	PortBindings []PortBinding `json:"portBindings"`

	// Privileged Whether the container runs in privileged mode.
	Privileged bool `json:"privileged"`

	// Resources Live resource usage for a container.
	Resources ContainerResources `json:"resources"`

	// RestartCount Number of times the container has been restarted.
	RestartCount int `json:"restartCount"`

	// RestartPolicy Container restart policy.
	RestartPolicy ContainerDetailRestartPolicy `json:"restartPolicy"`

	// StartedAt Time the container last started.
	StartedAt time.Time `json:"startedAt"`

	// Status Current state of a container.
	Status ContainerStatus `json:"status"`

	// VolumeBindings Bind mounts and volume mappings.
	VolumeBindings []VolumeMount `json:"volumeBindings"`
}

// ContainerDetailRestartPolicy Container restart policy.
type ContainerDetailRestartPolicy string

// ContainerList List of containers.
type ContainerList struct {
	// Items Containers matching the query. Empty array, never null.
	Items []Container `json:"items"`
}

// ContainerNetwork Network a container is attached to.
type ContainerNetwork struct {
	// Driver Network driver.
	Driver string `json:"driver"`

	// Name Network name.
	Name string `json:"name"`
}

// ContainerResources Live resource usage for a container.
type ContainerResources struct {
	// CpuPercent CPU usage as a percentage of total host CPU.
	CpuPercent float64 `json:"cpuPercent"`

	// MemoryBytes Current memory usage in bytes.
	MemoryBytes Bytes `json:"memoryBytes"`

	// MemoryPercent Memory usage as a percentage of total host memory.
	MemoryPercent float64 `json:"memoryPercent"`
}

// ContainerStatus Current state of a container.
type ContainerStatus string

// DockerImage A Docker image stored on a backend device.
type DockerImage struct {
	// Device Identifier of the backend device storing this image.
	Device string `json:"device"`

	// Id Globally unique image identifier in the form `{device}.{shortId}`,
	// where `shortId` is the first 12 characters of the image's SHA-256 digest.
	Id string `json:"id"`

	// Repository Full repository name. Includes the registry prefix for non-Docker Hub
	// images (e.g. `ghcr.io/immich-app/immich-server`). Docker Hub images
	// are stored without prefix (e.g. `caddy`).
	Repository string `json:"repository"`

	// Size On-disk size of the image in bytes.
	Size Bytes `json:"size"`

	// Tags Tags assigned to this image. Empty when the image is untagged.
	Tags []string `json:"tags"`
}

// DockerImageDetail defines model for DockerImageDetail.
type DockerImageDetail struct {
	// Created Timestamp when the image was built.
	Created time.Time `json:"created"`

	// Description Human-readable description of the image. Omitted when empty.
	Description *string `json:"description,omitempty"`

	// Device Identifier of the backend device storing this image.
	Device string `json:"device"`

	// Id Globally unique image identifier in the form `{device}.{shortId}`,
	// where `shortId` is the first 12 characters of the image's SHA-256 digest.
	Id string `json:"id"`

	// Repository Full repository name. Includes the registry prefix for non-Docker Hub
	// images (e.g. `ghcr.io/immich-app/immich-server`). Docker Hub images
	// are stored without prefix (e.g. `caddy`).
	Repository string `json:"repository"`

	// Size On-disk size of the image in bytes.
	Size Bytes `json:"size"`

	// Tags Tags assigned to this image. Empty when the image is untagged.
	Tags []string `json:"tags"`

	// VirtualSize Total uncompressed size of all image layers in bytes.
	VirtualSize Bytes `json:"virtualSize"`
}

// DockerImageList List of Docker images.
type DockerImageList struct {
	// Items Docker images matching the query. Empty array, never null.
	Items []DockerImage `json:"items"`
}

// DockerNetwork A Docker network on a backend device.
type DockerNetwork struct {
	// ConnectedContainers Number of containers currently connected to this network.
	ConnectedContainers int `json:"connectedContainers"`

	// Device Identifier of the backend device hosting this network.
	Device string `json:"device"`

	// Id Globally unique network identifier in the form `{device}.{name}`.
	// Use this value directly in path parameters.
	Id string `json:"id"`

	// Name Network name as reported by Docker.
	Name string `json:"name"`
}

// DockerNetworkDetail defines model for DockerNetworkDetail.
type DockerNetworkDetail struct {
	// ConnectedContainers Number of containers currently connected to this network.
	ConnectedContainers int `json:"connectedContainers"`

	// Containers Names of containers currently connected to this network.
	Containers []string `json:"containers"`

	// Device Identifier of the backend device hosting this network.
	Device string `json:"device"`

	// Driver Network driver (e.g. bridge, host, macvlan).
	Driver string `json:"driver"`

	// Gateway Default gateway IP. Omitted for networks without IPAM.
	Gateway *string `json:"gateway,omitempty"`

	// Id Globally unique network identifier in the form `{device}.{name}`.
	// Use this value directly in path parameters.
	Id string `json:"id"`

	// IpRange IP range allocated to containers within this subnet, in CIDR notation. Omitted when not configured.
	IpRange *string `json:"ipRange,omitempty"`

	// Name Network name as reported by Docker.
	Name string `json:"name"`

	// Subnet Subnet in CIDR notation. Omitted for networks without IPAM (e.g. host).
	Subnet *string `json:"subnet,omitempty"`
}

// DockerNetworkList List of Docker networks.
type DockerNetworkList struct {
	// Items Docker networks matching the query. Empty array, never null.
	Items []DockerNetwork `json:"items"`
}

// EnvVariable An environment variable set in a container.
type EnvVariable struct {
	// Key Environment variable name.
	Key string `json:"key"`

	// Value Environment variable value.
	Value string `json:"value"`
}

// PortBinding Port mapping between a container and the host.
type PortBinding struct {
	// ContainerPort Port exposed by the container.
	ContainerPort int `json:"containerPort"`

	// HostPort Port bound on the host.
	HostPort int `json:"hostPort"`

	// Protocol Transport protocol.
	Protocol PortBindingProtocol `json:"protocol"`
}

// PortBindingProtocol Transport protocol.
type PortBindingProtocol string

// Problem RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Problem struct {
	// Detail Human-readable explanation specific to this occurrence.
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference identifying the specific occurrence.
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code echoed for convenience.
	Status int `json:"status"`

	// Title Short, human-readable summary of the problem.
	Title string `json:"title"`

	// Type URI reference identifying the problem type.
	Type string `json:"type"`
}

// VolumeMount Bind mount or volume mapping for a container.
type VolumeMount struct {
	// Destination Mount path inside the container.
	Destination string `json:"destination"`

	// Mode Mount access mode — read-only or read-write.
	Mode VolumeMountMode `json:"mode"`

	// Source Host path or volume name.
	Source string `json:"source"`
}

// VolumeMountMode Mount access mode — read-only or read-write.
type VolumeMountMode string

// DeviceFilter defines model for DeviceFilter.
type DeviceFilter = string

// BadRequest RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type BadRequest = Problem

// Forbidden RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Forbidden = Problem

// InternalServerError RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type InternalServerError = Problem

// NotFound RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type NotFound = Problem

// TooManyRequests RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type TooManyRequests = Problem

// Unauthorized RFC 9457 Problem Details object. Returned as
// `application/problem+json` for all error responses. The `type` URI
// is the machine-readable error code; clients should key off `type`,
// not `title` (which is human-readable and may change).
type Unauthorized = Problem

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListContainersParams defines parameters for ListContainers.
type ListContainersParams struct {
	// Device Filter results to a specific backend device by its identifier.
	// Omit to return results from all devices.
	Device *DeviceFilter `form:"device,omitempty" json:"device,omitempty"`
}

// RestartContainerParams defines parameters for RestartContainer.
type RestartContainerParams struct {
	// IdempotencyKey Client-generated key to ensure the request is processed at most once.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// StartContainerParams defines parameters for StartContainer.
type StartContainerParams struct {
	// IdempotencyKey Client-generated key to ensure the request is processed at most once.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// StopContainerParams defines parameters for StopContainer.
type StopContainerParams struct {
	// IdempotencyKey Client-generated key to ensure the request is processed at most once.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// ListDockerImagesParams defines parameters for ListDockerImages.
type ListDockerImagesParams struct {
	// Device Filter results to a specific backend device by its identifier.
	// Omit to return results from all devices.
	Device *DeviceFilter `form:"device,omitempty" json:"device,omitempty"`
}

// ListDockerNetworksParams defines parameters for ListDockerNetworks.
type ListDockerNetworksParams struct {
	// Device Filter results to a specific backend device by its identifier.
	// Omit to return results from all devices.
	Device *DeviceFilter `form:"device,omitempty" json:"device,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListContainers request
	ListContainers(ctx context.Context, params *ListContainersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetContainer request
	GetContainer(ctx context.Context, containerId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RestartContainer request
	RestartContainer(ctx context.Context, containerId string, params *RestartContainerParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartContainer request
	StartContainer(ctx context.Context, containerId string, params *StartContainerParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopContainer request
	StopContainer(ctx context.Context, containerId string, params *StopContainerParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDockerImages request
	ListDockerImages(ctx context.Context, params *ListDockerImagesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDockerImage request
	GetDockerImage(ctx context.Context, imageId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListDockerNetworks request
	ListDockerNetworks(ctx context.Context, params *ListDockerNetworksParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDockerNetwork request
	GetDockerNetwork(ctx context.Context, networkId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListContainers(ctx context.Context, params *ListContainersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListContainersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetContainer(ctx context.Context, containerId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetContainerRequest(c.Server, containerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestartContainer(ctx context.Context, containerId string, params *RestartContainerParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestartContainerRequest(c.Server, containerId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartContainer(ctx context.Context, containerId string, params *StartContainerParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartContainerRequest(c.Server, containerId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StopContainer(ctx context.Context, containerId string, params *StopContainerParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopContainerRequest(c.Server, containerId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDockerImages(ctx context.Context, params *ListDockerImagesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDockerImagesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDockerImage(ctx context.Context, imageId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDockerImageRequest(c.Server, imageId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListDockerNetworks(ctx context.Context, params *ListDockerNetworksParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDockerNetworksRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDockerNetwork(ctx context.Context, networkId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDockerNetworkRequest(c.Server, networkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListContainersRequest generates requests for ListContainers
func NewListContainersRequest(server string, params *ListContainersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/containers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Device != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "device", *params.Device, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetContainerRequest generates requests for GetContainer
func NewGetContainerRequest(server string, containerId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "containerId", containerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/containers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRestartContainerRequest generates requests for RestartContainer
func NewRestartContainerRequest(server string, containerId string, params *RestartContainerParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "containerId", containerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/containers/%s:restart", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IdempotencyKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", *params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam0)
		}

	}

	return req, nil
}

// NewStartContainerRequest generates requests for StartContainer
func NewStartContainerRequest(server string, containerId string, params *StartContainerParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "containerId", containerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/containers/%s:start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IdempotencyKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", *params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam0)
		}

	}

	return req, nil
}

// NewStopContainerRequest generates requests for StopContainer
func NewStopContainerRequest(server string, containerId string, params *StopContainerParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "containerId", containerId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/containers/%s:stop", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IdempotencyKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", *params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam0)
		}

	}

	return req, nil
}

// NewListDockerImagesRequest generates requests for ListDockerImages
func NewListDockerImagesRequest(server string, params *ListDockerImagesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/images")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Device != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "device", *params.Device, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDockerImageRequest generates requests for GetDockerImage
func NewGetDockerImageRequest(server string, imageId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "imageId", imageId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/images/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListDockerNetworksRequest generates requests for ListDockerNetworks
func NewListDockerNetworksRequest(server string, params *ListDockerNetworksParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/networks")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Device != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "device", *params.Device, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDockerNetworkRequest generates requests for GetDockerNetwork
func NewGetDockerNetworkRequest(server string, networkId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "networkId", networkId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/docker/networks/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListContainersWithResponse request
	ListContainersWithResponse(ctx context.Context, params *ListContainersParams, reqEditors ...RequestEditorFn) (*ListContainersResponse, error)

	// GetContainerWithResponse request
	GetContainerWithResponse(ctx context.Context, containerId string, reqEditors ...RequestEditorFn) (*GetContainerResponse, error)

	// RestartContainerWithResponse request
	RestartContainerWithResponse(ctx context.Context, containerId string, params *RestartContainerParams, reqEditors ...RequestEditorFn) (*RestartContainerResponse, error)

	// StartContainerWithResponse request
	StartContainerWithResponse(ctx context.Context, containerId string, params *StartContainerParams, reqEditors ...RequestEditorFn) (*StartContainerResponse, error)

	// StopContainerWithResponse request
	StopContainerWithResponse(ctx context.Context, containerId string, params *StopContainerParams, reqEditors ...RequestEditorFn) (*StopContainerResponse, error)

	// ListDockerImagesWithResponse request
	ListDockerImagesWithResponse(ctx context.Context, params *ListDockerImagesParams, reqEditors ...RequestEditorFn) (*ListDockerImagesResponse, error)

	// GetDockerImageWithResponse request
	GetDockerImageWithResponse(ctx context.Context, imageId string, reqEditors ...RequestEditorFn) (*GetDockerImageResponse, error)

	// ListDockerNetworksWithResponse request
	ListDockerNetworksWithResponse(ctx context.Context, params *ListDockerNetworksParams, reqEditors ...RequestEditorFn) (*ListDockerNetworksResponse, error)

	// GetDockerNetworkWithResponse request
	GetDockerNetworkWithResponse(ctx context.Context, networkId string, reqEditors ...RequestEditorFn) (*GetDockerNetworkResponse, error)
}

type ListContainersResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *ContainerList
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ListContainersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListContainersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListContainersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetContainerResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *ContainerDetail
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetContainerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RestartContainerResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r RestartContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RestartContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RestartContainerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StartContainerResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r StartContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StartContainerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StopContainerResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r StopContainerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopContainerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StopContainerResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDockerImagesResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *DockerImageList
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ListDockerImagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDockerImagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDockerImagesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDockerImageResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *DockerImageDetail
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetDockerImageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDockerImageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDockerImageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListDockerNetworksResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *DockerNetworkList
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r ListDockerNetworksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDockerNetworksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDockerNetworksResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDockerNetworkResponse struct {
	Body                      []byte
	HTTPResponse              *http.Response
	JSON200                   *DockerNetworkDetail
	ApplicationproblemJSON400 *BadRequest
	ApplicationproblemJSON401 *Unauthorized
	ApplicationproblemJSON403 *Forbidden
	ApplicationproblemJSON404 *NotFound
	ApplicationproblemJSON429 *TooManyRequests
	ApplicationproblemJSON500 *InternalServerError
}

// Status returns HTTPResponse.Status
func (r GetDockerNetworkResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDockerNetworkResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDockerNetworkResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListContainersWithResponse request returning *ListContainersResponse
func (c *ClientWithResponses) ListContainersWithResponse(ctx context.Context, params *ListContainersParams, reqEditors ...RequestEditorFn) (*ListContainersResponse, error) {
	rsp, err := c.ListContainers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListContainersResponse(rsp)
}

// GetContainerWithResponse request returning *GetContainerResponse
func (c *ClientWithResponses) GetContainerWithResponse(ctx context.Context, containerId string, reqEditors ...RequestEditorFn) (*GetContainerResponse, error) {
	rsp, err := c.GetContainer(ctx, containerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetContainerResponse(rsp)
}

// RestartContainerWithResponse request returning *RestartContainerResponse
func (c *ClientWithResponses) RestartContainerWithResponse(ctx context.Context, containerId string, params *RestartContainerParams, reqEditors ...RequestEditorFn) (*RestartContainerResponse, error) {
	rsp, err := c.RestartContainer(ctx, containerId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestartContainerResponse(rsp)
}

// StartContainerWithResponse request returning *StartContainerResponse
func (c *ClientWithResponses) StartContainerWithResponse(ctx context.Context, containerId string, params *StartContainerParams, reqEditors ...RequestEditorFn) (*StartContainerResponse, error) {
	rsp, err := c.StartContainer(ctx, containerId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartContainerResponse(rsp)
}

// StopContainerWithResponse request returning *StopContainerResponse
func (c *ClientWithResponses) StopContainerWithResponse(ctx context.Context, containerId string, params *StopContainerParams, reqEditors ...RequestEditorFn) (*StopContainerResponse, error) {
	rsp, err := c.StopContainer(ctx, containerId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopContainerResponse(rsp)
}

// ListDockerImagesWithResponse request returning *ListDockerImagesResponse
func (c *ClientWithResponses) ListDockerImagesWithResponse(ctx context.Context, params *ListDockerImagesParams, reqEditors ...RequestEditorFn) (*ListDockerImagesResponse, error) {
	rsp, err := c.ListDockerImages(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDockerImagesResponse(rsp)
}

// GetDockerImageWithResponse request returning *GetDockerImageResponse
func (c *ClientWithResponses) GetDockerImageWithResponse(ctx context.Context, imageId string, reqEditors ...RequestEditorFn) (*GetDockerImageResponse, error) {
	rsp, err := c.GetDockerImage(ctx, imageId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDockerImageResponse(rsp)
}

// ListDockerNetworksWithResponse request returning *ListDockerNetworksResponse
func (c *ClientWithResponses) ListDockerNetworksWithResponse(ctx context.Context, params *ListDockerNetworksParams, reqEditors ...RequestEditorFn) (*ListDockerNetworksResponse, error) {
	rsp, err := c.ListDockerNetworks(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDockerNetworksResponse(rsp)
}

// GetDockerNetworkWithResponse request returning *GetDockerNetworkResponse
func (c *ClientWithResponses) GetDockerNetworkWithResponse(ctx context.Context, networkId string, reqEditors ...RequestEditorFn) (*GetDockerNetworkResponse, error) {
	rsp, err := c.GetDockerNetwork(ctx, networkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDockerNetworkResponse(rsp)
}

// ParseListContainersResponse parses an HTTP response from a ListContainersWithResponse call
func ParseListContainersResponse(rsp *http.Response) (*ListContainersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListContainersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ContainerList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetContainerResponse parses an HTTP response from a GetContainerWithResponse call
func ParseGetContainerResponse(rsp *http.Response) (*GetContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ContainerDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseRestartContainerResponse parses an HTTP response from a RestartContainerWithResponse call
func ParseRestartContainerResponse(rsp *http.Response) (*RestartContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RestartContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseStartContainerResponse parses an HTTP response from a StartContainerWithResponse call
func ParseStartContainerResponse(rsp *http.Response) (*StartContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseStopContainerResponse parses an HTTP response from a StopContainerWithResponse call
func ParseStopContainerResponse(rsp *http.Response) (*StopContainerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopContainerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseListDockerImagesResponse parses an HTTP response from a ListDockerImagesWithResponse call
func ParseListDockerImagesResponse(rsp *http.Response) (*ListDockerImagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDockerImagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DockerImageList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetDockerImageResponse parses an HTTP response from a GetDockerImageWithResponse call
func ParseGetDockerImageResponse(rsp *http.Response) (*GetDockerImageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDockerImageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DockerImageDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseListDockerNetworksResponse parses an HTTP response from a ListDockerNetworksWithResponse call
func ParseListDockerNetworksResponse(rsp *http.Response) (*ListDockerNetworksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDockerNetworksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DockerNetworkList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}

// ParseGetDockerNetworkResponse parses an HTTP response from a GetDockerNetworkWithResponse call
func ParseGetDockerNetworkResponse(rsp *http.Response) (*GetDockerNetworkResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDockerNetworkResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DockerNetworkDetail
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest TooManyRequests
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON429 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON500 = &dest

	}

	return response, nil
}
